# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = D:\cmake\bin\cmake.exe

# The command to remove a file.
RM = D:\cmake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Projects\WAP64

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Projects\WAP64

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	D:\cmake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	D:\cmake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /d D:\Projects\WAP64 && $(CMAKE_COMMAND) -E cmake_progress_start D:\Projects\WAP64\CMakeFiles D:\Projects\WAP64\libwap32\CMakeFiles\progress.marks
	cd /d D:\Projects\WAP64 && $(MAKE) -f CMakeFiles\Makefile2 libwap32/all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Projects\WAP64\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /d D:\Projects\WAP64 && $(MAKE) -f CMakeFiles\Makefile2 libwap32/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /d D:\Projects\WAP64 && $(MAKE) -f CMakeFiles\Makefile2 libwap32/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /d D:\Projects\WAP64 && $(MAKE) -f CMakeFiles\Makefile2 libwap32/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /d D:\Projects\WAP64 && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
libwap32/CMakeFiles/wap32.dir/rule:
	cd /d D:\Projects\WAP64 && $(MAKE) -f CMakeFiles\Makefile2 libwap32/CMakeFiles/wap32.dir/rule
.PHONY : libwap32/CMakeFiles/wap32.dir/rule

# Convenience name for target.
wap32: libwap32/CMakeFiles/wap32.dir/rule

.PHONY : wap32

# fast build rule for target.
wap32/fast:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/build
.PHONY : wap32/fast

src/buffer.obj: src/buffer.cpp.obj

.PHONY : src/buffer.obj

# target to build an object file
src/buffer.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/buffer.cpp.obj
.PHONY : src/buffer.cpp.obj

src/buffer.i: src/buffer.cpp.i

.PHONY : src/buffer.i

# target to preprocess a source file
src/buffer.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/buffer.cpp.i
.PHONY : src/buffer.cpp.i

src/buffer.s: src/buffer.cpp.s

.PHONY : src/buffer.s

# target to generate assembly for a file
src/buffer.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/buffer.cpp.s
.PHONY : src/buffer.cpp.s

src/errors.obj: src/errors.cpp.obj

.PHONY : src/errors.obj

# target to build an object file
src/errors.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/errors.cpp.obj
.PHONY : src/errors.cpp.obj

src/errors.i: src/errors.cpp.i

.PHONY : src/errors.i

# target to preprocess a source file
src/errors.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/errors.cpp.i
.PHONY : src/errors.cpp.i

src/errors.s: src/errors.cpp.s

.PHONY : src/errors.s

# target to generate assembly for a file
src/errors.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/errors.cpp.s
.PHONY : src/errors.cpp.s

src/io.obj: src/io.cpp.obj

.PHONY : src/io.obj

# target to build an object file
src/io.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/io.cpp.obj
.PHONY : src/io.cpp.obj

src/io.i: src/io.cpp.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/pid.obj: src/pid.cpp.obj

.PHONY : src/pid.obj

# target to build an object file
src/pid.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid.cpp.obj
.PHONY : src/pid.cpp.obj

src/pid.i: src/pid.cpp.i

.PHONY : src/pid.i

# target to preprocess a source file
src/pid.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid.cpp.i
.PHONY : src/pid.cpp.i

src/pid.s: src/pid.cpp.s

.PHONY : src/pid.s

# target to generate assembly for a file
src/pid.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid.cpp.s
.PHONY : src/pid.cpp.s

src/pid_read.obj: src/pid_read.cpp.obj

.PHONY : src/pid_read.obj

# target to build an object file
src/pid_read.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid_read.cpp.obj
.PHONY : src/pid_read.cpp.obj

src/pid_read.i: src/pid_read.cpp.i

.PHONY : src/pid_read.i

# target to preprocess a source file
src/pid_read.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid_read.cpp.i
.PHONY : src/pid_read.cpp.i

src/pid_read.s: src/pid_read.cpp.s

.PHONY : src/pid_read.s

# target to generate assembly for a file
src/pid_read.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid_read.cpp.s
.PHONY : src/pid_read.cpp.s

src/pid_write.obj: src/pid_write.cpp.obj

.PHONY : src/pid_write.obj

# target to build an object file
src/pid_write.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid_write.cpp.obj
.PHONY : src/pid_write.cpp.obj

src/pid_write.i: src/pid_write.cpp.i

.PHONY : src/pid_write.i

# target to preprocess a source file
src/pid_write.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid_write.cpp.i
.PHONY : src/pid_write.cpp.i

src/pid_write.s: src/pid_write.cpp.s

.PHONY : src/pid_write.s

# target to generate assembly for a file
src/pid_write.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/pid_write.cpp.s
.PHONY : src/pid_write.cpp.s

src/utils.obj: src/utils.cpp.obj

.PHONY : src/utils.obj

# target to build an object file
src/utils.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/utils.cpp.obj
.PHONY : src/utils.cpp.obj

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/wwd.obj: src/wwd.cpp.obj

.PHONY : src/wwd.obj

# target to build an object file
src/wwd.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd.cpp.obj
.PHONY : src/wwd.cpp.obj

src/wwd.i: src/wwd.cpp.i

.PHONY : src/wwd.i

# target to preprocess a source file
src/wwd.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd.cpp.i
.PHONY : src/wwd.cpp.i

src/wwd.s: src/wwd.cpp.s

.PHONY : src/wwd.s

# target to generate assembly for a file
src/wwd.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd.cpp.s
.PHONY : src/wwd.cpp.s

src/wwd_read.obj: src/wwd_read.cpp.obj

.PHONY : src/wwd_read.obj

# target to build an object file
src/wwd_read.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd_read.cpp.obj
.PHONY : src/wwd_read.cpp.obj

src/wwd_read.i: src/wwd_read.cpp.i

.PHONY : src/wwd_read.i

# target to preprocess a source file
src/wwd_read.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd_read.cpp.i
.PHONY : src/wwd_read.cpp.i

src/wwd_read.s: src/wwd_read.cpp.s

.PHONY : src/wwd_read.s

# target to generate assembly for a file
src/wwd_read.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd_read.cpp.s
.PHONY : src/wwd_read.cpp.s

src/wwd_write.obj: src/wwd_write.cpp.obj

.PHONY : src/wwd_write.obj

# target to build an object file
src/wwd_write.cpp.obj:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd_write.cpp.obj
.PHONY : src/wwd_write.cpp.obj

src/wwd_write.i: src/wwd_write.cpp.i

.PHONY : src/wwd_write.i

# target to preprocess a source file
src/wwd_write.cpp.i:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd_write.cpp.i
.PHONY : src/wwd_write.cpp.i

src/wwd_write.s: src/wwd_write.cpp.s

.PHONY : src/wwd_write.s

# target to generate assembly for a file
src/wwd_write.cpp.s:
	cd /d D:\Projects\WAP64 && $(MAKE) -f libwap32\CMakeFiles\wap32.dir\build.make libwap32/CMakeFiles/wap32.dir/src/wwd_write.cpp.s
.PHONY : src/wwd_write.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... wap32
	@echo ... src/buffer.obj
	@echo ... src/buffer.i
	@echo ... src/buffer.s
	@echo ... src/errors.obj
	@echo ... src/errors.i
	@echo ... src/errors.s
	@echo ... src/io.obj
	@echo ... src/io.i
	@echo ... src/io.s
	@echo ... src/pid.obj
	@echo ... src/pid.i
	@echo ... src/pid.s
	@echo ... src/pid_read.obj
	@echo ... src/pid_read.i
	@echo ... src/pid_read.s
	@echo ... src/pid_write.obj
	@echo ... src/pid_write.i
	@echo ... src/pid_write.s
	@echo ... src/utils.obj
	@echo ... src/utils.i
	@echo ... src/utils.s
	@echo ... src/wwd.obj
	@echo ... src/wwd.i
	@echo ... src/wwd.s
	@echo ... src/wwd_read.obj
	@echo ... src/wwd_read.i
	@echo ... src/wwd_read.s
	@echo ... src/wwd_write.obj
	@echo ... src/wwd_write.i
	@echo ... src/wwd_write.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /d D:\Projects\WAP64 && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

